<?php

namespace App\Support;

class ApiErrorCode
{
    public const UNAUTHORIZED = 'UNAUTHORIZED';
    public const VALIDATION_ERROR = 'VALIDATION_ERROR';
    public const EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND';
    public const EMPLOYEE_INACTIVE = 'EMPLOYEE_INACTIVE';
    public const WEEK_PERIOD_NOT_FOUND = 'WEEK_PERIOD_NOT_FOUND';
    public const DAILY_WAGE_NOT_FOUND = 'DAILY_WAGE_NOT_FOUND';
    public const DAILY_WAGE_DUPLICATE = 'DAILY_WAGE_DUPLICATE';
    public const DAILY_WAGE_LOCKED = 'DAILY_WAGE_LOCKED';
    public const WEEK_ALREADY_FULLY_PAID = 'WEEK_ALREADY_FULLY_PAID';
    public const PAYMENT_ALREADY_COMPLETED = 'PAYMENT_ALREADY_COMPLETED';
    public const PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND';
    public const SYNC_CONFLICT = 'SYNC_CONFLICT';
    public const FORBIDDEN_ACTION = 'FORBIDDEN_ACTION';
    public const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
}

